// flow-typed signature: b82cb22721cdf3796bd2cd1acd21f9d6
// flow-typed version: <<STUB>>/@types/cheerio_v^0.22.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/cheerio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/cheerio' {
  declare module.exports: any;
}
